parameters:

services:
    _defaults:
        autowire: true      # Automatically inject dependencies
        autoconfigure: true # Automatically registers services as commands, event subscribers, etc.

    # Register all classes in src/ as services
    App\:
        resource: '../src/'

    # Bind the OfferRepositoryInterface to the Doctrine implementation
    App\Offer\Domain\OfferRepositoryInterface:
        alias: App\Offer\Infrastructure\Doctrine\OfferRepository
        public: false
